# src/main/resources/application.conf

slick.dbs.default.profile = "slick.jdbc.PostgresProfile$"
slick.dbs.default.db {
  url = "jdbc:postgresql://localhost:5432/test_db"
  user = "postgres"
  password = "Dilshan@123"
  driver = "org.postgresql.Driver"
  connectionPool = "HikariCP"
}
